### ISSUE TITLE
naive dns

### ISSUE THREAD

**Issue by happy201807** [quintus-lab/OpenWRT-R2S-R4S#10]
hi, when I use the built-in helloworld to use naive, the three dns options cannot be resolved normally, the server is built with this script (https://github.com/proxysu/ProxySU), what dns software support is needed for naive normal work? Thank you.

**Comment by quintus-lab** [comment]
I have no idea for naiveproxy.
If another naiveproxy client can work with your naiveproxy server, it means there's something wrong with SSR-Plus,
report it and wait for upstream updates.

Alternatively, you can try SmartDNS

**Comment by happy201807** [comment]
希望能支持 OpenWrt 原生编译 #111

**Comment by happy201807** [comment]
希望能支持 OpenWrt 原生编译 #111
