### ISSUE TITLE
Add the fastest way only for China specific

### ISSUE THREAD

**Issue by happy201807** [quintus-lab/OpenWRT-R2S-R4S#8]
Hi, I noticed that trojan go is not included in ssr+. Can I add it to the compilation configuration file? If so, which patch do I need to add to the source code, and then it can be fully compiled?

**Comment by quintus-lab** [comment]
Here it is.
![image](https://user-images.githubusercontent.com/31897806/105610973-a44bde80-5ded-11eb-8161-f1b6a17fe533.png)

CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan-go=y

**Comment by happy201807** [comment]
https://github.com/pymumu/smartdns
DNS is another very important part of accelerating the network access experience. If I want to add the smartdns package independently, what needs to be done? What patches need to be added?

**Comment by quintus-lab** [comment]
First, put the 2 lines in 01-prepare_package.sh:
#SmartDNS
svn co https://github.com/pymumu/smartdns/trunk/package/openwrt package/new/smartdns/smartdns
svn co https://github.com/project-openwrt/openwrt/branches/openwrt-19.07/package/ntlf9t/luci-app-smartdns package/new/smartdns/luci-app-smartdns

then, add 2 lines to r4s.seed:
CONFIG_PACKAGE_luci-app-smartdns=y
CONFIG_PACKAGE_smartdns=y

**Comment by happy201807** [comment]
Thanks.You're nice to have around.
